views/admin.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session, abort
from werkzeug.security import check_password_hash
from core.models import Transaction, Account, User, TimeDeposit, Log, DoesNotExist
from playhouse.shortcuts import model_to_dict
from core.forms import LoginForm, TransactionForm, TransferForm, InquiryForm, TimeDepositForm
from core.wrappers import admin_auth

from datetime import datetime, timedelta

bp = Blueprint('admin', __name__)

@bp.route('/')
@admin_auth
def index():
    time_deposits = TimeDeposit.select().where((TimeDeposit.terminal_date <= datetime.now()) & (TimeDeposit.deleted == False)).execute()
    history = Transaction.select().order_by(Transaction.created_at.desc()).execute()
    for time_deposit in time_deposits:
        Account.update(
            account = Account.balance + (time_deposit.amount * time_deposit.interest)
        ).where(Account.account_number == time_deposit.account_number).execute()

        TimeDeposit.update(
            deleted = True
        ).where(TimeDeposit.id == time_deposit.id).execute()

    return render_template('admin/index.html', history=history)
    
@bp.route('/deposit', methods=['GET', 'POST'])
@admin_auth
def deposit():
    form = TransactionForm(request.form)
    if form.validate_on_submit():
        Account.update(
            balance = Account.balance + form.amount.data,
            updated_at = datetime.now()
        ).where(Account.account_number == form.account_number.data).execute()

        Transaction.insert(
            account_number = form.account_number.data,
            reference_number = form.account_number.data,
            amount = form.amount.data,
            type = 'DEPOSIT'
        ).execute()
        flash('Deposit successful')
        return redirect(url_for('admin.deposit'))
    return render_template('admin/deposit.html', form=form)

@bp.route('/time_deposit', methods=['GET', 'POST'])
@admin_auth
def time_deposit():
    form = TimeDepositForm(request.form)
    form.duration.choices = ([
        (3, '3 months (7.0% interest)'),
        (6, '6 months (8.0% interest)'),
        (12, '12 months (9.0% interest)')
    ])

    if form.validate_on_submit():
        interest_ref = {
            3: 7.0,
            6: 8.0,
            12: 9.0
        }

        Account.update(
            balance = Account.balance + form.amount.data,
            updated_at = datetime.now()
        ).where(Account.account_number == form.account_number.data).execute()

        TimeDeposit.insert(
            account_number = form.account_number.data,
            amount = form.amount.data,
            interest = interest_ref[form.duration.data],
            terminal_date = datetime.now() + timedelta(days=form.duration.data*30)
        ).execute()

        Transaction.insert(
            account_number = form.account_number.data,
            reference_number = form.account_number.data,
            amount = form.amount.data,
            type = 'TIME DEPOSIT'
        ).execute()
        flash('Time Deposit successful')
        return redirect(url_for('admin.time_deposit'))
    return render_template('admin/time_deposit.html', form=form)

@bp.route('/withdraw', methods=['GET', 'POST'])
@admin_auth
def withdraw():
    form = TransactionForm(request.form)
    if form.validate_on_submit():
        account = Account.get(Account.account_number == form.account_number.data)

        if account.balance - form.amount.data <= 0:
            flash('Withdraw amount is greater than account remaining balance')
            
        else:
            Account.update(
                balance = Account.balance - form.amount.data,
                updated_at = datetime.now()
            ).where(Account.account_number == form.account_number.data).execute()

            Transaction.insert(
                account_number = form.account_number.data,
                reference_number = form.account_number.data,
                amount = form.amount.data,
                type = 'WITHDRAW'
            ).execute()
            flash('Withdraw successful')

        return redirect(url_for('admin.withdraw'))
    return render_template('admin/withdraw.html', form=form)

@bp.route('/transfer', methods=['GET', 'POST'])
@admin_auth
def transfer():
    form = TransferForm(request.form)
    if form.validate_on_submit():
        sender_account = Account.get(Account.account_number == form.sender_account_number.data)
        receiver_account = Account.get(Account.account_number == form.receiver_account_number.data)

        Account.update(
            balance = Account.balance - form.amount.data,
            updated_at = datetime.now()
        ).where(Account.account_number == form.sender_account_number.data).execute()

        Account.update(
            balance = Account.balance + form.amount.data,
            updated_at = datetime.now()
        ).where(Account.account_number == form.receiver_account_number.data).execute()

        Transaction.insert(
            account_number = form.sender_account_number.data,
            reference_number = form.receiver_account_number.data,
            amount = form.amount.data,
            type = 'FUND TRANSFER'
        ).execute()
        flash('Fund Transfer successful')
        return redirect(url_for('admin.transfer'))
    return render_template('admin/transfer.html', form=form)

@bp.route('/inquiry', methods=['GET', 'POST'])
@admin_auth
def inquiry():
    form = InquiryForm(request.form)
    account = None
    if form.validate_on_submit():
        account = Account.select(
            User.first_name,
            User.last_name,
            Account.balance,
        ).join(User, attr='user').where(
            (Account.account_number == form.account_number.data)
        ).get()

    return render_template('admin/inquiry.html', form=form, account=account)

views/main.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session, abort
from werkzeug.security import check_password_hash
from core.models import Transaction, Account, User, TimeDeposit, Log, DoesNotExist
from playhouse.shortcuts import model_to_dict
from core.forms import LoginForm, TransactionForm, UserTransferForm, InquiryForm, TimeDepositForm
from core.wrappers import authenticated

from datetime import datetime, timedelta

bp = Blueprint('main', __name__)

@bp.route('/')
@authenticated
def index():
    time_deposits = TimeDeposit.select().where((TimeDeposit.terminal_date <= datetime.now()) & (TimeDeposit.deleted == False)).execute()

    for time_deposit in time_deposits:
        Account.update(
            account = Account.balance + (time_deposit.amount * time_deposit.interest) + time_deposit.amount
        ).where(Account.account_number == time_deposit.account_number).execute()

        TimeDeposit.update(
            deleted = True
        ).where(TimeDeposit.id == time_deposit.id).execute()

    accounts = Account.select().where(Account.user_id == session['user']['id']).execute()
    transactions = len(Transaction.select(Transaction)
        .join(Account, on=(Transaction.account_number == Account.account_number))
        .join(User, on=(Account.user_id == User.id))
        .where(User.id == session['user']['id'])
        .dicts()
    )

    return render_template('main/index.html', accounts=accounts, transactions=transactions)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.get_or_none(User.email_address == form.email_address.data)
        if user and check_password_hash(user.password, form.password.data):
            Log.insert(
                user_id = user.id,
                action = 'LOGIN'
            ).execute()

            if user.type <= 2:
                session['admin'] = model_to_dict(user)
                return redirect(url_for('admin.index'))
            else:
                session['user'] = model_to_dict(user)
                return redirect(url_for('main.index'))
            flash("Welcome back, {}!".format(user.first_name))
    return render_template('main/login.html', form=form)

@bp.route('/logout', methods=['GET', 'POST'])
def logout():
    if 'user' in session:
        user = session['user']
        session.pop('user')
    elif 'admin' in session:
        user = session['admin']
        session.pop('admin')

    Log.insert(
        user_id = user['id'],
        action = 'LOGOUT'
    ).execute()
    return redirect(url_for('main.login'))

@bp.route('/history')
@authenticated
def history():
    transactions = (Transaction.select(Transaction)
        .join(Account, on=(Transaction.account_number == Account.account_number))
        .join(User, on=(Account.user_id == User.id))
        .where(User.id == session['user']['id'])
        .execute()
    )
    return render_template('main/history.html', transactions=transactions)

@bp.route('/transfer', methods=['GET', 'POST'])
@authenticated
def transfer():
    accounts = Account.select().where((Account.user_id == session['user']['id']) & (Account.type != 3)).execute()

    form = UserTransferForm(request.form)
    form.sender_account_number.choices = [(account.account_number, "{} ({})".format(account.account_number, 'Savings' if account.type == 1 else 'ATM')) for account in accounts]
    if form.validate_on_submit():
        sender_account = Account.get(Account.account_number == form.sender_account_number.data)
        receiver_account = Account.get(Account.account_number == form.receiver_account_number.data)

        Account.update(
            balance = Account.balance - form.amount.data,
            updated_at = datetime.now()
        ).where(Account.account_number == form.sender_account_number.data).execute()

        Account.update(
            balance = Account.balance + form.amount.data,
            updated_at = datetime.now()
        ).where(Account.account_number == form.receiver_account_number.data).execute()

        Transaction.insert(
            account_number = form.sender_account_number.data,
            reference_number = form.receiver_account_number.data,
            amount = form.amount.data,
            type = 'FUND TRANSFER'
        ).execute()
        flash('Fund Transfer successful')
        return redirect(url_for('main.transfer'))
    return render_template('main/transfer.html', form=form)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/materialize.min.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>
        body {
            font-family: 'Raleway', sans-serif;
        }

        .full-height {
            height: 100vh;
        }
    </style>
    {% block navbar_css %}
    <style>
        header,
        main,
        footer {
            padding-left: 300px;
        }

        @media only screen and (max-width: 992px) {
            header,
            main,
            footer {
                padding-left: 0;
            }
        }
    </style>
    {% endblock %}
    {% block css %} {% endblock %}

    <title>QABanking</title>
</head>

<body>
    {% block navbar %}
    <header>
        <nav class="z-depth-1">
            <div class="nav-wrapper blue darken-2 z-depth-0">
                <div class="container">
                    <a href="#" data-target="slide-out" class="sidenav-trigger">
                        <i class="material-icons">menu</i>
                    </a>
                    <a href="#" class="brand-logo">QABanking</a>
                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                        <li>
                            <a href="{{ url_for('main.index') }}"><i class="material-icons left">home</i>Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <ul id="slide-out" class="sidenav sidenav-fixed">
        <li class="blue darken-2">
            <div class="section">
                <h4 class="center-align white-text">
                    D Bank
                </h4>
            </div>
            <div class="divider"></div>
        </li>

        <li>
            <a href="{{ url_for('main.index') }}" class="waves-effect"><i class="material-icons">home</i>Home</a>
        </li>
        {% if session['user']['type'] == 3 %}
        <li>
            <div class="divider"></div>
        </li>
        <li>
            <a class="subheader">Transactions</a>
        </li>
        <li>
            <a class="waves-effect" href="{{ url_for('main.deposit') }}"><i class="material-icons">arrow_upwards</i>Deposit</a>
        </li>
        <li>
            <a class="waves-effect" href="{{ url_for('main.withdraw') }}"><i class="material-icons">arrow_downwards</i>Withdraw</a>
        </li>
        <li>
            <a class="waves-effect" href="{{ url_for('main.time_deposit') }}"><i class="material-icons">access_time</i>Time Deposit</a>
        </li>
        <li>
            <a class="waves-effect" href="{{ url_for('main.inquiry') }}"><i class="material-icons">account_balance_wallet</i>Balance Inquiry</a>
        </li>
        <li>
            <a class="waves-effect" href="{{ url_for('main.transfer') }}"><i class="material-icons">swap_horizontal</i>Fund Transfer</a>
        </li>
        <li>
            <a class="waves-effect" href="{{ url_for('main.history') }}"><i class="material-icons">history</i>History</a>
        </li>
        {% endif %}
        <li>
            <div class="divider"></div>
        </li>
        <li>
            <a class="subheader">Management</a>
        </li>
        {% if session['user']['type'] == 1 %}
        <li>
            <a class="waves-effect" href="{{ url_for('user.index') }}"><i class="material-icons">account_box</i>User Management</a>
        </li>
        {% endif %}
        <li>
            <a class="waves-effect" href="{{ url_for('account.index') }}"><i class="material-icons">account_balance</i>Account Management</a>
        </li>
        <li>
            <div class="divider"></div>
        </li>
        <li>
            <a class="waves-effect" href="{{ url_for('main.logout') }}"><i class="material-icons">exit_to_app</i>Logout</a>
        </li>
    </ul>
    {% endblock %} 
    
    <main>
        {% block notifications %}
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="section">
                <div class="container">
                    {% for message in messages %}
                    <div class="card-panel light-blue white-text">
                        <!-- <h5>
                            Notifications
                            <i class="material-icons right" onclick="closeNotification(event)">close</i>
                        </h5>
                        <br> -->
                        <!-- <p> -->
                            {{ message }}
                        <!-- </p> -->
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            {% endwith %}
        {% endblock %}
        {% block content %} {% endblock %}
    </main>

    <script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/materialize.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('.sidenav').sidenav();
        });

        function closeNotification(e) {
            e.preventDefault();
            $(e.target).closest('.section').fadeOut();
        }
    </script>
    {% block script %} {% endblock %}
</body>

</html>