views/teller.py
from flask import Blueprint, render_template, request, session, flash, redirect, url_for
from werkzeug.security import check_password_hash, generate_password_hash
from playhouse.shortcuts import model_to_dict
from core.forms import TellerLoginForm, ChangePinForm, TransactionForm
from core.wrappers import teller_auth
from core.models import Account, User, Transaction, Log, fn, DoesNotExist

from datetime import datetime, time

bp = Blueprint('teller', __name__)

@bp.route('/')
@teller_auth
def index():
    return render_template('teller/index.html')

@bp.route('/inquiry')
@teller_auth
def inquiry():
    balance = "{0:,.2f}".format(Account.get(Account.id == session['atm_auth']).balance)
    return render_template('teller/inquiry.html', balance=balance)

@bp.route('/withdraw', methods=['GET', 'POST'])
@teller_auth
def withdraw():
    if request.method == 'POST':
        account = Account.get(Account.id == session['atm_auth'])

        total_amount = (Transaction.select(fn.Sum(Transaction.amount).alias('amounts'))
            .where(
                (Transaction.account_number == account.account_number) & 
                (Transaction.created_at >= datetime.combine(datetime.today(), time.min)) & 
                (Transaction.type == 'ATM WITHDRAW')
            )
            .get()
        ).amounts or 0

        if float(total_amount) + float(request.form.get('amount')) > 25000:
            flash('You have reached the daily maximum withdraw limit')

        elif int(request.form.get('amount')) < 500:
            flash('Amount must be greater than Php 500.00')

        else:
            Account.update(balance = Account.balance - request.form.get('amount')).where(Account.id == session['atm_auth']).execute()

            Transaction.insert(
                account_number = account.account_number,
                reference_number = account.account_number,
                amount = request.form.get('amount'),
                type = 'ATM WITHDRAW'
            ).execute()
            
            return redirect(url_for('teller.inquiry'))
    return render_template('teller/withdraw.html')

@bp.route('/deposit', methods=['GET', 'POST'])
@teller_auth
def deposit():
    if request.method == 'POST':
        account = Account.get(Account.id == session['atm_auth'])

        Account.update(balance = Account.balance + request.form.get('amount')).where(Account.id == session['atm_auth']).execute()

        Transaction.insert(
            account_number = account.account_number,
            reference_number = account.account_number,
            amount = request.form.get('amount'),
            type = 'ATM DEPOSIT'
        ).execute()

        return redirect(url_for('teller.inquiry'))
    return render_template('teller/deposit.html')

@bp.route('/transfer', methods=['GET', 'POST'])
@teller_auth
def transfer():
    form = TransactionForm(request.form)
    if form.validate_on_submit():
        account = Account.get(Account.id == session['atm_auth'])

        if form.account_number.data == account.account_number:
            flash('You cannot transfer funds to your own account')

        else:
            Account.update(balance = Account.balance - form.amount.data).where(Account.id == session['atm_auth']).execute()
            Account.update(balance = Account.balance + form.amount.data).where(Account.account_number == form.account_number.data).execute()

            Transaction.insert(
                account_number = account.account_number,
                reference_number = form.account_number.data,
                amount = request.form.get('amount'),
                type = 'ATM FUND TRANSFER'
            ).execute()

            return redirect(url_for('teller.inquiry'))
    return render_template('teller/transfer.html', form=form)

@bp.route('/change_pin', methods=['GET', 'POST'])
@teller_auth
def change_pin():
    form = ChangePinForm(request.form)
    if form.validate_on_submit():
        account = Account.get(Account.id == session['atm_auth'])

        if check_password_hash(account.pin, form.current_pin.data):
            Account.update(
                pin = generate_password_hash(form.new_pin.data)
            ).where(Account.id == session['atm_auth']).execute()

            flash('PIN successfully updated')
            return redirect(url_for('teller.index'))
        else:
            flash('PIN does not match')
    return render_template('teller/change_pin.html', form=form)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = TellerLoginForm(request.form)
    if form.validate_on_submit():
        account = Account.get_or_none((Account.account_number == form.account_number.data) & (Account.deleted == False))

        if account and check_password_hash(account.pin, form.password.data):
            session['atm_auth'] = account.id

            return redirect(url_for('teller.index'))
        else:
            flash('Invalid Account Number and PIN')
    return render_template('teller/login.html', form=form)

@bp.route('/logout')
@teller_auth
def logout():
    session.pop('atm_auth')
    return redirect(url_for('teller.login'))

templates/teller/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/materialize.min.css') }}">
    <style>
        body {
            font-family: 'Raleway', sans-serif;
        }

        .full-height {
            height: 100vh;
        }

        .btn-block {
            display: block;
            margin-bottom: 0.5rem;
        }
    </style>
    {% block css %} {% endblock %}

    <title>QABank | ATM</title>
</head>

<body class="blue darken-2">
    <main class="full-height valign-wrapper row" style="margin-bottom: 0rem;">
        <div class="col s12 row">
            <div class="container col s12 m6 offset-m3">
                {% with messages = get_flashed_messages() %} {% if messages %}
                <div class="section">
                    <div class="row justify-content-center">
                        {% for message in messages %}
                        <div class="col-sm-12 col-md-6 card card-body bg-danger text-white">
                            {{ message }}
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% endif %} {% endwith %}
                <div class="section">
                    <h2 class="white-text center-align"><b>QAB</b>ank</h2>
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>
    </main>

    <script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/materialize.min.js') }}"></script>
    {% block script %} {% endblock %}
</body>

</html>

templates/teller/change_pin.html
{% extends 'teller/base.html' %} {% block content %}
<form id="changePinForm" action="{{ url_for('teller.change_pin') }}" method="POST">
    {{ form.csrf_token }}
    <div class="card">
        <div class="card-content">
            <h2 class="card-title">Change PIN</h2>
            <div class="input-field">
                {{ form.current_pin.label }} {{ form.current_pin(class_='validate') }} {% for error in form.current_pin.errors %}
                <small class="red-text">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="input-field">
                {{ form.new_pin.label }} {{ form.new_pin(class_='validate') }} {% for error in form.new_pin.errors %}
                <small class="red-text">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="input-field">
                {{ form.confirm_pin.label }} {{ form.confirm_pin(class_='validate') }} {% for error in form.confirm_pin.errors %}
                <small class="red-text">{{ error }}</small>
                {% endfor %}
            </div>
            <center>
                <a href="{{ url_for('teller.index') }}" class="btn-large waves-effect blue darken-2">
                    <i class="material-icons left">keyboard_arrow_left</i>Back
                </a>
                <button type="submit" class="btn-large waves-effect blue darken-2">
                    <i class="material-icons left">send</i>Enter
                </a>
            </center>
        </div>
    </div>
</form>
{% endblock %}

templates/teller/deposit.html
{% extends 'teller/base.html' %} {% block content %}
<form action="{{ url_for('teller.deposit') }}" method="POST">
    <div class="card">
        <div class="card-content">
            <h2 class="card-title">Deposit</h2>
            <div class="row">
                <div class="input-field col s12 m9">
                    <input type="number" name="amount" id="amountField" class="form-control" min="0" max="25000">
                    <label for="amountField">Enter Amount</label>
                </div>
                <div class="col s12 m3">
                    <center>
                        <button class="btn-large waves-effect blue darken-2">
                            <i class="material-icons left">send</i>Enter
                        </button>
                    </center>
                </div>
            </div>
            <center>
                <a href="{{ url_for('teller.index') }}" class="btn-large waves-effect blue darken-2">
                    <i class="material-icons left">keyboard_arrow_left</i>Back
                </a>
            </center>
        </div>
    </div>
</form>
{% endblock %}

templates/teller/index.html
{% extends 'teller/base.html' %} {% block content %}
<div class="card-panel">
    <div class="row" style="margin-bottom: 0rem;">
        <div class="col s6">
            <a href="{{ url_for('teller.withdraw') }}" class="btn-large btn-block waves-effect blue darken-2">withdraw</a>
            <a href="{{ url_for('teller.inquiry') }}" class="btn-large btn-block waves-effect blue darken-2">Balance Inquiry</a>
            <a href="{{ url_for('teller.transfer') }}" class="btn-large btn-block waves-effect blue darken-2">Fund Transfer</a>
        </div>
        <div class="col s6">
            <a href="{{ url_for('teller.deposit') }}" class="btn-large btn-block waves-effect blue darken-2">Deposit</a>
            <a href="{{ url_for('teller.change_pin') }}" class="btn-large btn-block waves-effect blue darken-2">Change PIN</a>
            <a href="{{ url_for('teller.logout') }}" class="btn-large btn-block waves-effect blue darken-2">Exit</a>
        </div>
    </div>
</div>
{% endblock %}

templates/teller/inquiry.html
{% extends 'teller/base.html' %} {% block content %}
<div class="card">
    <div class="card-content">
        <h2 class="card-title">Balance Inquiry</h2>
        <h2 class="center-align blue-text text-darken-2">&#8369; {{ balance }}</h2>
        <div class="section"></div>
        <center>
            <a href="{{ url_for('teller.logout') }}" class="btn-large waves-effect blue darken-2">
                <i class="material-icons left">exit_to_app</i>Exit
            </a>
            <a href="{{ url_for('teller.index') }}" class="btn-large waves-effect blue darken-2">
                <i class="material-icons left">repeat</i>Another Transaction
            </a>
        </center>
    </div>
</div>
{% endblock %}

templates/teller/login.html
{% extends 'teller/base.html' %} {% block content %}
<form id="loginForm" action="{{ url_for('teller.login') }}" method="post">
    {{ form.csrf_token }}
    <div class="card-panel">
        <div class="input-field">
            {{ form.account_number(class_='validate') }} {{ form.account_number.label }} {% for error in form.account_number.errors %}
            <small class="red-text">{{ error }}</small>
            {% endfor %}
        </div>
        <div class="input-field">
            {{ form.password.label }} {{ form.password(class_='validate', maxlength='6') }} {% for error in form.password.errors %}
            <small class="red-text">{{ error }}</small>
            {% endfor %}
        </div>
        <center>
            <button type="submit" class="btn-large waves-effect blue darken-2">
                <i class="material-icons left">send</i>Login
            </button>
        </center>
    </div>
</form>
{% endblock %}

templates/teller/transfer.html
{% extends 'teller/base.html' %} {% block content %}
<form id="transferForm" action="{{ url_for('teller.transfer') }}" method="POST">
    {{ form.csrf_token }}
    <div class="card">
        <div class="card-content">
            <h2 class="card-title">Fund Transfer</h2>
            <div class="input-field">
                    {{ form.account_number(class_='validate') }} {{ form.account_number.label }} {% for error in form.account_number.errors
                %}
                <small class="red-text">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="input-field">
                {{ form.amount(class_='validate') }} {{ form.amount.label }} {% for error in form.amount.errors %}
                <small class="red-text">{{ error }}</small>
                {% endfor %}
            </div>
            <center>
                <a href="{{ url_for('teller.index') }}" class="btn-large waves-effect blue darken-2">
                    <i class="material-icons left">keyboard_arrow_left</i>Back
                </a>
                <button type="submit" class="btn-large waves-effect blue darken-2">
                    <i class="material-icons left">send</i>Enter
                </button>
            </center>
        </div>
    </div>
</form>
{% endblock %}

templates/teller/withdraw.html
{% extends 'teller/base.html' %} {% block content %}
<form action="{{ url_for('teller.withdraw') }}" method="POST">
    <div class="card">
        <div class="card-content">
            <h2 class="card-title">Withdraw</h2>
            <div class="row">
                <div class="input-field col s12 m9">
                    <input type="number" name="amount" id="amountField" class="form-control" min="0" max="25000">
                    <label for="amountField">Enter Amount</label>
                </div>
                <div class="col s12 m3">
                    <center>
                        <button class="btn-large waves-effect blue darken-2">
                            <i class="material-icons left">send</i>Enter
                        </button>
                    </center>
                </div>
            </div>
            <center>
                <a href="{{ url_for('teller.index') }}" class="btn-large waves-effect blue darken-2">
                    <i class="material-icons left">keyboard_arrow_left</i>Back
                </a>
            </center>
        </div>
    </div>
</form>
{% endblock %}