views/user.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash
from core.models import User
from core.forms import CreateUserForm, UpdateUserForm, ChangePasswordForm
from core.wrappers import admin_auth

from datetime import datetime

bp = Blueprint('user', __name__)

@bp.route('/')
@admin_auth
def index():
    users = User.select().execute()
    return render_template('user/index.html', users=users)

@bp.route('/view/<int:id>')
@admin_auth
def view(id):
    user = User.get(User.id == id)
    return render_template('user/view.html', user=user)

@bp.route('/create', methods=['GET', 'POST'])
@admin_auth
def create():
    form = CreateUserForm(request.form)
    if form.validate_on_submit():
        User.insert(
            first_name = form.first_name.data,
            middle_name = form.middle_name.data,
            last_name = form.last_name.data,
            email_address = form.email_address.data,
            phone_number = form.phone_number.data,
            address = form.address.data,
            birth_date = form.birth_date.data,
            type = form.type.data,
            password = generate_password_hash(form.password.data),
        ).execute()
        flash('User successfully registered')
        return redirect(url_for('user.index'))
    return render_template('user/create.html', form=form)

@bp.route('/update/<int:id>', methods=['GET', 'POST'])
@admin_auth
def update(id):
    form = UpdateUserForm(request.form)
    user = User.get(User.id == id)
    if form.validate_on_submit():
        User.update(
            first_name = form.first_name.data,
            middle_name = form.middle_name.data,
            last_name = form.last_name.data,
            email_address = form.email_address.data,
            phone_number = form.phone_number.data,
            address = form.address.data,
            birth_date = form.birth_date.data,
            type = form.type.data,
            updated_at=datetime.now()
        ).where(User.id == id).execute()
        flash('User successfully updated')
        return redirect(url_for('user.index'))
    return render_template('user/update.html', form=form, user=user)

@bp.route('/change_password', methods=['GET', 'POST'])
@admin_auth
def change_password():
    form = ChangePasswordForm(request.form)
    if form.validate_on_submit():
        User.update(
            password = generate_password_hash(form.new_password.data),
        ).where(User.id == form.user_id.data).execute()
        flash('Password successfully changed')
        return redirect(url_for('user.index'))
    return render_template('user/password.html', form=form)

@bp.route('/deactivate/<int:id>')
@admin_auth
def deactivate(id):
    User.update(
        deleted=True,
        updated_at=datetime.now()
    ).where(User.id == id).execute()
    return redirect(url_for('user.index'))

@bp.route('/activate/<int:id>')
@admin_auth
def activate(id):
    User.update(
        deleted=False,
        updated_at=datetime.now()
    ).where(User.id == id).execute()
    return redirect(url_for('user.index'))

templates/user/create.html
{% extends 'admin/base.html' %} {% block content %}
<div class="container">
    <form action="{{ url_for('user.create') }}" method="post">
        {{ form.csrf_token }}
        <div class="box box-solid box-primary">
            <div class="box-header">
                <h3 class="box-title">Create New User</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-sm-12 col-md-4">
                        {{ form.first_name.label }}
                        <div class="form-group">
                            {{ form.first_name(class_='form-control') }} {% for error in form.first_name.errors %}
                            <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-4">
                        {{ form.middle_name.label }}
                        <div class="form-group">
                            {{ form.middle_name(class_='form-control') }} {% for error in form.middle_name.errors %}
                            <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-4">
                        {{ form.last_name.label }}
                        <div class="form-group">
                            {{ form.last_name(class_='form-control') }} {% for error in form.last_name.errors %}
                            <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        {{ form.email_address.label }}
                        <div class="form-group">
                            {{ form.email_address(class_='form-control') }} {% for error in form.email_address.errors %}
                            <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        {{ form.phone_number.label }}
                        <div class="form-group">
                            {{ form.phone_number(class_='form-control') }} {% for error in form.phone_number.errors %}
                            <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-12">
                        {{ form.address.label }}
                        <div class="form-group">
                            {{ form.address(class_='form-control') }} {% for error in form.address.errors %}
                            <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-8">
                        {{ form.birth_date.label }}
                        <div class="form-group">
                            {{ form.birth_date(class_='form-control') }} {% for error in form.birth_date.errors %}
                            <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-4">
                        <div class="form-group">
                            {{ form.type.label }} {{ form.type(class_='form-control') }} {% for error in form.type.errors %}
                            <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        {{ form.password.label }}
                        <div class="form-group">
                            {{ form.password(class_='form-control') }} {% for error in form.password.errors %}
                            <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        {{ form.confirm_password.label }}
                        <div class="form-group">
                            {{ form.confirm_password(class_='form-control') }} {% for error in form.confirm_password.errors %}
                            <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <a href="{{ url_for('user.index') }}" class="btn btn-default">
                    Back</a>
                <button type="submit" class="btn btn-primary">
                    Submit</button>
            </div>
    </form>
    </div>
    {% endblock %}

templates/user/index.html
{% extends 'admin/base.html' %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">
                        User Manager
                    </h3>
                </div>
                <div class="box-body">
                    <table id="userTable">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email Address</th>
                                <th>Phone Number</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <th>{{ user.id }}</th>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.email_address }}</td>
                                <td>{{ user.phone_number }}</td>
                                <td>{{ 'Active' if not user.deleted else 'Inactive' }}</td>
                                <td>
                                    <div class="btn-group">
                                        <a href="{{ url_for('user.update', id=user.id) }}" class="btn btn-sm btn-primary">Update</a>
                                        {% if user.deleted %}
                                        <a href="{{ url_for('user.activate', id=user.id) }}" class="btn btn-sm btn-success">Activate</a>
                                        {% else %}
                                        <a href="{{ url_for('user.deactivate', id=user.id) }}" class="btn btn-sm btn-danger">Deactivate</a>
                                        {% endif %}
                                        <a href="{{ url_for('user.view', id=user.id) }}" class="btn btn-sm btn-info">View</a>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/datatables.min.css') }}"> {% endblock %} {% block script %}
<script src="{{ url_for('static', filename='js/datatables.min.js') }}"></script>
<script>
    $('#userTable').DataTable();
</script>
{% endblock %}

templates/user/password.html
{% extends 'admin/base.html' %} {% block content %}
<div class="container">
    <form action="{{ url_for('user.change_password') }}" method="post">
        {{ form.csrf_token }}
        <div class="box box-solid box-primary">
            <div class="box-header">
                <h3 class="box-title">Change Password</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="form-group col-sm-12 col-md-6">
                            {{ form.user_id.label }} {{ form.user_id(class_='form-control') }} {% for error in form.user_id.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                            {{ form.current_password.label }} {{ form.current_password(class_='form-control') }} {% for error in form.current_password.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <hr>
                    <div class="form-group col-sm-12 col-md-6">
                            {{ form.new_password.label }} {{ form.new_password(class_='form-control') }} {% for error in form.new_password.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                            {{ form.confirm_password.label }} {{ form.confirm_password(class_='form-control') }} {% for error in form.confirm_password.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <a href="{{ url_for('user.index') }}" class="btn btn-default">
                    Back</a>
                <button type="submit" class="btn btn-primary">
                    Submit</button>
            </div>
    </form>
</div>
{% endblock %}

templates/user/update.html
{% extends 'admin/base.html' %} {% block content %}
<div class="container">
    <form action="{{ url_for('user.update', id=user.id) }}" method="post">
        {{ form.csrf_token }}
        <div class="box box-solid box-primary">
            <div class="box-header">
                <h3 class="box-title">Update User</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="form-group col-sm-12 col-md-4">
                            {{ form.first_name.label }} {{ form.first_name(class_='form-control', value=user.first_name) }} {% for error in form.first_name.errors
                        %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group col-sm-12 col-md-4">
                            {{ form.middle_name.label }} {{ form.middle_name(class_='form-control', value=user.middle_name) }} {% for error in form.middle_name.errors
                        %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group col-sm-12 col-md-4">
                            {{ form.last_name.label }} {{ form.last_name(class_='form-control', value=user.last_name) }} {% for error in form.last_name.errors
                        %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                            {{ form.email_address.label }} {{ form.email_address(class_='form-control', value=user.email_address) }} {% for error in form.email_address.errors
                        %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                            {{ form.phone_number.label }} {{ form.phone_number(class_='form-control', value=user.phone_number) }} {% for error in form.phone_number.errors
                        %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group col-sm-12">
                            {{ form.address.label }} {{ form.address(class_='form-control', value=user.address) }} {% for error in form.address.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group col-sm-12 col-md-8">
                            {{ form.birth_date.label }} {{ form.birth_date(class_='form-control', value=user.birth_date) }} {% for error in form.birth_date.errors
                        %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group col-sm-12 col-md-4">
                            {{ form.type.label }} {{ form.type(class_='form-control', value=user.type) }} {% for error in form.type.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="box-footer">
                    <a href="{{ url_for('user.index') }}" class="btn btn-default">
                        Back</a>
                    <button type="submit" class="btn btn-primary">
                        Submit</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
<script>
    $(function() {
        $('select#type option[value="{{ user.type}}"]').prop('selected', true);
    });
</script>
{% endblock %}

templates/user/view.html
{% extends 'admin/base.html' %} {% block content %}
<div class="container">
    <div class="box box-solid box-primary">
        <div class="box-header">
            <h3 class="box-title">View User Profile</h3>
        </div>
        <div class="box-body">
            <h4>Personal Information</h4>
            <div class="row">
                <div class="col-sm-12 col-md-4">
                    <h5 class="text-primary">{{ user.first_name }}</h5>
                    <small>First Name</small>
                </div>
                <div class="col-sm-12 col-md-4">
                    <h5 class="text-primary">{{ user.middle_name }}</h5>
                    <small>Middle Name</small>

                </div>
                <div class="col-sm-12 col-md-4">
                    <h5 class="text-primary">{{ user.last_name }}</h5>
                    <small>Last Name</small>

                </div>
                <div class="col-sm-12 col-md-12">
                    <h5 class="text-primary">{{ user.birth_date }}</h5>
                    <small>Birth Date</small>
                </div>
            </div>
            <hr>
            <h4>Contact Information</h4>
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <h5 class="text-primary">{{ user.email_address }}</h5>
                    <small>Email Address</small>
                </div>
                <div class="col-sm-12 col-md-6">
                    <h5 class="text-primary">{{ user.phone_number }}</h5>
                    <small>Phone Number</small>
                </div>
            </div>
            <hr>
            <h4 class="card-title blue-text">User Account Informations</h4>
            <div class="row">
                <div class="col-sm-12 col-md-4">
                    <h5 class="text-primary">{{ user.created_at }}</h5>
                    <small>Creation Date</small>
                </div>
                <div class="col-sm-12 col-md-4">
                    <h5 class="text-primary">{{ user.updated_at }}</h5>
                    <small>Update Date</small>
                </div>
                <div class="col-sm-12 col-md-4">
                    <h5 class="text-primary">{{ 'Active' if not user.deleted else 'Inactive' }}</h5>
                    <small>Status</small>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <a href="{{ url_for('user.index') }}" class="btn btn-default">
                Back</a>
        </div>
    </div>
</div>
{% endblock %}